/// <reference path="Examples/Brainfuck/References.ts"/>
/// <reference path="Examples/BiteScript/References.ts"/>
/// <reference path="Examples/Calculator/References.ts"/>
/// <reference path="Examples/Common rules/Index.ts"/>
/// <reference path="Examples/INI Reader/References.ts"/>
/// <reference path="Examples/JSON Reader/References.ts"/>
/// <reference path="Tests/CycleDetection.ts"/>
/// <reference path="Tests/GrammerTests.ts"/>
/// <reference path="Tests/Suggestions.ts"/>
/// <reference path="Rule.ts"/>