[package]
name = "grammar"
version = "0.8.2"
authors = ["Vincent van Ingen <code@abitvin.net>"]

[dependencies]
# rule = { version = "0.8.1", git = "https://github.com/abitvin/rule-rust" }
rule = { version = "0.8.1", path = "../rule-rust" }