[package]
name = "grammar"
version = "0.14.3"
authors = ["Vincent van Ingen <code@abitvin.com>"]
edition = "2021"

[dependencies]
rule = { version = "0.14.2", git = "https://github.com/abitvin/rule-rust" }
