[package]
name = "grammar"
version = "0.14.1"
authors = ["Vincent van Ingen <code@abitvin.com>"]
edition = "2018"

[dependencies]
rule = { version = "0.13.1", git = "https://github.com/abitvin/rule-rust" }
